title = "Catherina configuration file"

[main_params]
input_data_dir = "./data/input"
output_data_dir = "./data/output/catherina"
climate_data_dir = "cmip6_data"
bcorr_path = "bias_correction/ERA5_benchmark_100tracks_bias_corrections.csv"
country_shp_path = "country_data/50m_cultural/ne_50m_admin_0_countries.shp"
start_year = 2025
end_year = 2100 
# start_year = 1980 # historical
# end_year = 2015 # historical
bias_correction = true
proj_crs = "EPSG: 3857" #Web-Mercator projection
n_seeds = 50 #standard value
n_jobs = 8
batch_seeds_size=2
models = ["ACCESS-CM2"] #Only 1
experiments = ["ssp585"] # Only 1 
# experiments = ["historical"] # Change years to run on historical
my_models = [
"cmcc_cm2_sr5",
"miroc_es2l",
"access_cm2",
"access_esm1_5",
"hadgem3_gc31_ll",
"hadgem3_gc31_mm",
"mpi_esm1_2_lr",
"ciesm",
"cesm2",
"inm_cm4_8",
"inm_cm5_0",
"taiesm1",
"sam0_unicon",
"ukesm1_0_ll",
"kiost_esm",
"cmcc_esm2",
"fgoals_g3"
] # sample with all variables required for cyclone tracks simulations

# Unused: all climate models
#models = [
#    "cnrm_cm6_1",
#    "cnrm_esm2_1",
#    "cnrm_esm2_1",
#    "cams_csm1_0",
#    "cmcc_cm2_sr5",
#    "ipsl_cm5a2_inca",
#    "ipsl_cm6a2_lr",
#    "miroc_es2h",
#    "miroc_es2l",
#    "access_cm2",
#    "access_esm1_5",
#    "canesm5",
#    "canesm5_canoe",
#    "hadgem3_gc31_ll",
#    "hadgem3_gc31_mm",
#    "mpi_esm1_2_lr",
#    "ec_earth3_aerchem",
#    "ec_earth3_cc",
#    "ec_earth3_veg_lr",
#    "bcc_esm1",
#    "bcc_csm2_mr",
#    "giss_e2_1_g",
#    "giss_e2_1_h",
#    "ciesm",
#    "cesm2",
#    "noresm2_mm",
#    "noresm2_lm",
#    "inm_cm4_8",
#    "inm_cm5_0",
#    "taiesm1",
#    "iitm_esm",
#    "kace_1_0_g",
#    "sam0_unicon",
#    "ukesm1_0_ll",
#    "kiost_esm",
#    "cmcc_esm2",
#    "fgoals_g3",
#    "fgoals_f3_l",
#]

[generation]
wind_thresh = 35.0
resolution=1
max_steps=175
ibtracs_path = "ibtracs.since1980.list.v04r01.csv"
fit_dir = "fit"



[intensification]
ne_10m_land_zip_path = "ne_10m_land.zip"
ne_10m_coastline_zip_path = "ne_10m_coastline.zip"


[damages]
level = "national"
source = "litpop"
buffer_dist = 0.25
func = "RMSF"
start_year = 2025
group_country = true 
sectors = ['aluminum','bauxite-mining','chemicals','coal-mining','copper-mining','iron-mining','manure-management','petrochemicals','power','rice-cultivation','steel', 'cement']
# climate model
models = ["access_cm2", "miroc_es2l", "ukesm1_0_ll"]
# climate scenario
scenarios =  ["ssp2_2_6", "ssp2_4_5", "ssp5_8_5"]
country_rmsf_corr_path = "D:/datasets_physical_risk/catherina_sectoral_dataset_refactor/input/fit/country_rmsf_corr.xlsx"
