from catherina_damage.damage_along_tracks import get_damage_tracks
from catherina_comparison.damage_plot import (read_damage_files,
                                              plot_damage_scenarios,
                                              plot_damage_increase_loess,
                                              plot_damage_increase_loess_grouped)
import pandas as pd

MODEL = ["mpi_esm1_2_lr",
         "ukesm1_0_ll",
         "miroc_es2l",
         "fgoals_g3",
         "ipsl_cm5a2_inca",
         "access_cm2"]

MODE = "local"  # Mode ('local' or 'S3') for data retrieval and writing

N_YEARS = 25
START_YEAR = [2025, 2050, 2075]  # Start year (histo: 1980, ssp: 2050)
KEEP_HIST = True
READ_PER_SEED = False # To target all_seeds files generated by computing damages of all seeds in one file

def main():
    df_damage_fin = pd.DataFrame(columns=['SSP_RCP', 'year', 'seed',
                                          'SED', 'SED_sqrt', 'SED_third',
                                          'SED_pop', 'SED_gdp', 'SED_none',
                                          'model', 'iso3'])
    for year in START_YEAR:
        df_damage_year = pd.DataFrame(columns=['SSP_RCP', 'year', 'seed',
                                              'SED', 'SED_sqrt', 'SED_third',
                                              'SED_pop', 'SED_gdp', 'SED_none',
                                              'model','iso3'])
        for i in MODEL:
            df = get_damage_tracks(mode=MODE,
                           model=i,
                           start_year=year,
                           N_years=N_YEARS,
                           keep_hist=KEEP_HIST,
                           read_per_seed=READ_PER_SEED)

            df_damage = read_damage_files(df, mode=MODE)
            df_damage['model'] = i
            df_damage_year = pd.concat([df_damage_year, df_damage])

        df_damage_fin = pd.concat([df_damage_fin, df_damage_year])

    plot_damage_scenarios(df_damage_fin)
    plot_damage_increase_loess(df_damage_fin, metric='90%', remove_outliers=True)
    plot_damage_increase_loess(df_damage_fin, metric='mean', remove_outliers=True)


if __name__ == "__main__":
    main()
