
from catherina_damage.damage_along_tracks import get_damage_tracks
from catherina_comparison.damage_plot import read_damage_files

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

MODEL = ["mpi_esm1_2_lr",
         "ukesm1_0_ll",
         "miroc_es2l",
         "fgoals_g3",
         "ipsl_cm5a2_inca",
         "access_cm2"]

MODE = "local"  # Mode ('local' or 'S3') for data retrieval and writing

N_YEARS = 25
START_YEAR = 2050  # Start year (histo: 1980, ssp: 2050)
KEEP_HIST = True
READ_PER_SEED = False # To target all_seeds files generated by computing damages of all seeds in one file

def main():
    df_damage_fin = pd.DataFrame(columns=['SSP_RCP', 'year', 'seed',
                                          'SED', 'SED_sqrt', 'SED_third',
                                          'SED_pop', 'SED_gdp', 'SED_none',
                                          'model'])
    for i in MODEL:
        df = get_damage_tracks(mode=MODE,
                           model=i,
                           start_year=START_YEAR,
                           N_years=N_YEARS,
                           keep_hist=KEEP_HIST,
                           read_per_seed=READ_PER_SEED)

        df_damage = read_damage_files(df, mode=MODE, aggregate=False)
        df_damage['model'] = i
        df_damage_fin = pd.concat([df_damage_fin, df_damage])

    data = df_damage_fin[(df_damage_fin['iso3'].isin(['USA', 'AUS',
                                                      'CHN', 'MEX', 'JPN',
                                                      'TWN', 'KOR', 'IND',
                                                      'THA']))]

    data['SED'] = data['SED'] / 1e9

    # Define the SSP_RCP order
    ssp_rcp_order = ['historical', 'SSP2-RCP45',
                     'SSP3-RCP70', 'SSP4-RCP34',
                     'SSP5-RCP85']
    data['SSP_RCP'] = pd.Categorical(data['SSP_RCP'],
                                     categories=ssp_rcp_order,
                                     ordered=True)

    # Initialize a dictionary to keep track of the positions for each region
    annotation_positions = {}

    def plot_with_percentile(data, color, annotation_positions, **kwargs):
        # Identify the region
        region = data['iso3'].iloc[0]

        # Initialize the position list for this region if it's the first time
        if region not in annotation_positions:
            annotation_positions[region] = []

        # Calculate the 95th percentile
        percentile_95 = np.percentile(data['SED'], 95)
        plt.axvline(x=percentile_95, color=color, linestyle='--')

        # Find an unoccupied vertical position for the annotation
        ylim = plt.gca().get_ylim()
        text_y_position = ylim[1]
        while any(abs(pos - text_y_position) < 0.05 * (ylim[1] - ylim[0]) for pos in annotation_positions[region]):
            text_y_position -= 0.05 * (ylim[1] - ylim[0])

        # Update the positions list
        annotation_positions[region].append(text_y_position)

        # Annotate the percentile value
        plt.text(percentile_95, text_y_position,
                 f'{percentile_95:.2f}',
                 color=color, verticalalignment='top',
                 horizontalalignment='right')

    # Create the FacetGrid
    g = sns.FacetGrid(data, col="iso3",
                      col_wrap=3, hue="SSP_RCP",
                      margin_titles=True, height=3,
                      aspect=1)

    # Map the histogram plot to the grid
    g.map(sns.histplot, "SED", kde=True, bins=25, linewidth=0.2,
          multiple='stack', stat="density", log_scale=True, alpha=0.1)

    # Map the custom plotting function for the 95th percentile
    g.map_dataframe(plot_with_percentile,
                    annotation_positions=annotation_positions)

    # Get the legend elements
    handles, labels = g._legend_data.values(), g._legend_data.keys()

    # Add legend manually to one of the subplots (for example, the third subplot)
    g.axes.flat[0].legend(handles, labels, loc='upper left')

    # Adjust the layout
    g.fig.subplots_adjust(top=0.9)
    plt.savefig("outputs/distrib_country.png", dpi=200)
    # Show plot
    plt.show()



if __name__ == "__main__":
    main()
